server:
  port: 8001
  servlet:
    context-path: /
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study-cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 451311677zxg
mybatis:
  mapper-locations: classpath:mapper/*.xml

  type-aliases-package: com.zxg.springcloud.entities #所有Entity别名类所在包